version: '2'
services:

    # docker run --name postgis -e POSTGRES_PASSWORD=password -e POSTGRES_USER=user -p 5432:5432 -d mdillon/postgis
    db:
      # https://hub.docker.com/r/mdillon/postgis/
      # image: mdillon/postgis:9.6-alpine
      build: ./docker/postgis/

      hostname: postgis
      volumes:
#        - ./docler/postgis/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./postgis:/var/lib/postgresql
      # uncomment this to expose port 5432 to the host
      # WARNING: THIS IS UNSAFE USE ONLY FOR DEV
      ports:
        - "0.0.0.0:${TUTORIAL_GRPC_PG_PORT}:5432"
      # network_mode: "host"
      environment:
        - POSTGRES_USER:'docker'
        - POSTGRES_PASSWORD:'docker'
        - POSTGRES_DB:'test'
      restart: on-failure:5

    #
    # docker run -d --name graphite --restart=always -p 80:80 -p 2003-2004:2003-2004 -p 2023-2024:2023-2024 -p 8125:8125/udp -p 8126:8126 hopsoft/graphite-statsd
    graphite:
      image: hopsoft/graphite-statsd
      hostname: graphite
      ports:
        # -p 80:80 -p 2003-2004:2003-2004 -p 2023-2024:2023-2024 -p 8125:8125/udp -p 8126:8126
        - "0.0.0.0:80:80"
        - "0.0.0.0:${TUTORIAL_GRPC_GRAPHITE_PORT}:81"
        - "0.0.0.0:2005-2006:2003-2004"
        - "0.0.0.0:2023-2024:2023-2024"
        - "0.0.0.0:8125:8125/udp"
        - "0.0.0.0:8126:8126"
#       network_mode: "host"

    # CONSUL
    # docker run --net=host consul agent -server -ui -bootstrap -bind=127.0.0.1
    consul:
      image: consul
      container_name: "consul"
      hostname: "consul"
      network_mode: "host"
#      ports:
#        - "8500:8500/udp"
      # https://docs.docker.com/compose/compose-file/compose-file-v2/#command
      command: ["agent", "-server", "-ui", "-bootstrap", "-bind=127.0.0.1"]

#    consul:
#      image: "progrium/consul:latest"
#      container_name: "consul"
#      hostname: "consul"
#      ports:
#        - "8400:8400"
#        - "8500:8500"
##        - "8600:53"
#        - "8600:8600"
#      network_mode: "host"
#      command: "-server -bootstrap-expect 3 -ui-dir /ui"

    jupyter:
      # image: continuumio/anaconda/jupyternotebook
      build: ./docker/jupyter/
      ports:
        - "127.0.0.1:8888:8888"
      volumes:
        - ".:/opt/notebooks/2017_GRPC_Tutorial"
      network_mode: "host"
