CREATE DATABASE test;

-- CREATE USER user;
-- GRANT ALL PRIVILEGES ON DATABASE test TO user;

CREATE USER docker WITH PASSWORD 'docker';
GRANT ALL PRIVILEGES ON DATABASE test TO docker;

-- CREATE USER docker WITH PASSWORD 'jw8s0F4';
-- CREATE DATABASE test;
-- GRANT ALL PRIVILEGES ON DATABASE test TO docker;

CREATE EXTENSION postgis;